version: '3.8'

services:
  backend:
    image: gobackend
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - PORT=8000
      - REDIS_HOST=redis
      - POSTGRES_HOST=26db
      - POSTGRES_PASSWORD=example
    command: ["./server"]
    ports:
      - "8000:8000"
    build: .
    container_name: 26backend
  frontend:
    image: javafront
    command: "serve -s -l 5000 build"
    ports:
      - "5000:5000"
    build: .
    container_name: 26frontend
  redis:
    image: redis
    command: "redis-server --save 60 1 --loglevel warning"
    build: .
    container_name: 26redis
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: 26db
    volumes:
      - ./database:/var/lib/postgresql/data


