version: '3.8'

services:
  backend:
    image: gobackend
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - PORT=8000
    command: ["./server"]
    ports:
      - "8000:8000"
    build: .
    container_name: backend
  frontedd:
    image: javafront
    command: "serve -s -l 5000 build"
    ports:
      - "5000:5000"
    build: .
    container_name: frontend
